name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK Packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-31"
          sdkmanager "build-tools;31.0.2"

      - name: Grant Permission
        run: chmod +x "./CANVAS_4.4/CANVAS 4.4/CANVAS ALL FIX /NIKON/gradlew"

      - name: Build APK
        run: |
          cd "./CANVAS_4.4/CANVAS 4.4/CANVAS ALL FIX /NIKON"
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: '**/*.apk'
